title:              闲云野鹤
email:              weiweitop@qq.com
description:        青箬笠，绿蓑衣，斜风细雨不须归。
author:             伟哥
baseurl:            ""
url:                "https://weiweitop.fun" #the base hostname & protocol for your site that used by sitemap.xml

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:

# GitHub OAuth
github_oauth_clientID: 8723fc7ceb376b620fcd
github_oauth_clientSecret: 7f88152de61d21c972c54bcc7ea5a553188c4fb2

# Gitalk settings
repo: weiweitop.github.io
repo_owner: weiweitop
repo_admin: weiweitop


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-146221080-1

# baidu analytics
baidu_analytics: 32e47284c5ae43fc363d0b8da8303944

# Build settings
permalink:          pretty
markdown:           kramdown
paginate:           10
paginate_path:      /page:num

# GitHub Pages gem ignores all plugins included in the Gemfile, have to add them here. But seo, paginate works
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
