title:              闲云野鹤
email:              weiweitop@qq.com
description:        青箬笠，绿蓑衣，斜风细雨不须归。
author:             伟哥
baseurl:            ""
url:                "https://xxx.com"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:

# OAuth for Gitalk
clientID: 8723fc7ceb376b620fcd
clientSecret: 7f88152de61d21c972c54bcc7ea5a553188c4fb2

# Gitalk settings
repo: weiweitop.github.io
repo_owner: weiweitop
repo_admin: weiweitop


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
permalink:          pretty
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
